### ISSUE TITLE
Compile error on latest version of v8?

### ISSUE THREAD

**Issue by vote539** [walling/node-rsvg#10]
Thanks, especially to anru, for maintaining this module.

I've been using this module for a few months without issues, but then today, all of a sudden I'm getting a strange error when I run `npm install librsvg`.  I'm on OS X El Capitan.

```
In file included from ../src/Rsvg.cc:2:
../src/Rsvg.h:7:27: error: expected class name
class Rsvg : public node::ObjectWrap {
                          ^
../src/Rsvg.h:15:41: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/path/to/.node-gyp/4.6.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
```

I ran `npm install librsvg` only after receiving this other error after updating Node:

```
/path/to/node_modules/librsvg/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/path/to/node_modules/librsvg/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/path/to/node_modules/librsvg/index.js:3:34)
    at Module._compile (module.js:570:32)
```

Any ideas what's going wrong?  Thanks.

**Comment by vote539** [comment]
I switched around my Node symlinks and ended up getting the error to go away.  Sorry for the noise.
