### ISSUE TITLE
Can't install rsvg

### ISSUE THREAD

**Issue by dandaka** [walling/node-rsvg#6]
dandaka-mbp:html dandaka$ npm install rsvg
npm WARN package.json Gulp-scaffold@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/rsvg
npm http 304 https://registry.npmjs.org/rsvg

> rsvg@0.2.5 install /Users/dandaka/projects/oco-web/html/node_modules/rsvg
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config --libs-only-l librsvg-2.0 cairo-png cairo-pdf cairo-svg' returned exit status 127.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dandaka/projects/oco-web/html/node_modules/rsvg
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! rsvg@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsvg@0.2.5 install script.
npm ERR! This is most likely a problem with the rsvg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls rsvg
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "rsvg"
npm ERR! cwd /Users/dandaka/projects/oco-web/html
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/dandaka/projects/oco-web/html/npm-debug.log
npm ERR! not ok code 0
dandaka-mbp:html dandaka$ node-gyp rebuild
-bash: node-gyp: command not found
dandaka-mbp:html dandaka$ npm owner ls rsvg
npm http GET https://registry.npmjs.org/rsvg
npm http 304 https://registry.npmjs.org/rsvg
walling bwp@bwp.dk

**Comment by dandaka** [comment]
I've installed RSVG with Homebrew. But it did't help. Still same output.

**Comment by ghost** [comment]
I'm also getting this as well.

**Comment by arianrashidi** [comment]
Me too.

**Comment by kamilsk** [comment]
+1 :(

**Comment by leibnizli** [comment]
+1

**Comment by gkathan** [comment]
holy crap - me too... no solution in the horizon ?

**Comment by patternleaf** [comment]
FWIW just uninstalling and reinstalling pkg-config via brew fixed this for me.

I also got an error that the post-install step did not succeed. Uninstalling and reinstalling libffi seemed to make that happy.

However I now am seeing issue #7. So.

**Comment by ali-habibzadeh** [comment]
+1

**Comment by codetker** [comment]
+1

**Comment by rissell** [comment]
+1

**Comment by rissell** [comment]
@patternleaf This worked for me also to insta librsvg, solving problems with cordova and sugarcrm mobile sdk
